### ISSUE TITLE
D R COX 翻译讨论 （第一轮翻译中）

### ISSUE THREAD

**Issue by zyylvs** [cosname/conversation#10]
进度管理：陈舒瑶 @typewind
一轮翻译：陈舒瑶 @typewind
二轮翻译：Gloria @Wande-4
三轮翻译：虚位以待

欢迎大家一起参与！

**Comment by Wande-4** [comment]
二轮：Gloria

**Comment by COStudy** [comment]
我把@typewind 列为进度管理员了。主要协调整个流程，先后的衔接之类的，有点像项目经理。

不知@typewind 时间允许吗？

**Comment by typewind** [comment]
> 我把@typewind 列为进度管理员了。主要协调整个流程，先后的衔接之类的，有点像项目经理。
> 
> 不知@typewind 时间允许吗？

嗯，我一般周末和英国时间的晚上都是有空的，先试试看，有问题再交流

**Comment by Wande-4** [comment]
请问我是会从系统接收到pull request吗？到现在都没有动静，担心落下任务。

**Comment by typewind** [comment]
> 请问我是会从系统接收到pull request吗？到现在都没有动静，担心落下任务。

是我的锅，这周我这边有点突发状况，周六晚上前应该能给出第一版

**Comment by zyylvs** [comment]
@Wande-4 
> 请问我是会从系统接收到pull request吗？到现在都没有动静，担心落下任务。

有pull request后，系统管理员会合入到资料库。
你需要按照群里的操作指导V1.1，获取到最新资料。

**Comment by COStudy** [comment]
@typewind 进展如何啊？有任何问题请随时提出哈~
