### ISSUE TITLE
Efron翻译讨论（第一轮翻译中）

### ISSUE THREAD

**Issue by bored2020** [cosname/conversation#7]
冯裕祺@bored2020  认领Efron一轮翻译

进度管理：虚位以待
一轮翻译：冯裕祺@bored2020 
二轮翻译：@wangdepin 
三轮翻译：虚位以待

**Comment by taiyun** [comment]
@bored2020 要不兼任下进度管理啊~

**Comment by bored2020** [comment]
最近在忙开题，实在无法兼任，望谅解。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年12月3日(周五) 下午4:15
收件人: ***@***.***&gt;;
抄送: "Yuqi ***@***.******@***.***&gt;;
主题: Re: [cosname/conversation] Efron翻译讨论 (Issue #7)




 
@bored2020 要不兼任下进度管理啊~
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by wangdepin** [comment]
二轮翻译报名

**Comment by COStudy** [comment]
@wangdepin 添加到名单啦~

**Comment by COStudy** [comment]
@bored2020 理解理解，祝开题顺利，论文顺利，毕业顺利！

进度管理员虚位以待哈，欢迎勇士报名~

**Comment by COStudy** [comment]
@bored2020 进展如何啊~

**Comment by bored2020** [comment]
上周开始了，这周开题就结束了，能加快进度了😁



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年12月27日(周一) 下午2:12
收件人: ***@***.***&gt;;
抄送: "Yuqi ***@***.******@***.***&gt;;
主题: Re: [cosname/conversation] Efron翻译讨论 (Issue #7)




 
@bored2020 进展如何啊~
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by COStudy** [comment]
已完成。
